package com.rayyan.tesseract.agent;

import com.rayyan.tesseract.blueprint.Blueprint;
import com.rayyan.tesseract.blueprint.CompiledBlueprint;
import com.rayyan.tesseract.selection.Selection;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Shared context object for a single player's in-progress build.
 *
 * All agents read from and write to this object. No agent calls another
 * agent directly — all communication is through BuildState.
 *
 * Thread safety: all field mutations must happen on the Minecraft server thread
 * (preserve the existing whenComplete → player.getServer().execute() pattern).
 * The one exception is eventLog, which uses CopyOnWriteArrayList so it can be
 * safely read from any thread for logging.
 */
public final class BuildState {

    // ---- Identity ----
    UUID playerId;
    /** Nullable — may be null for web-triggered builds or after player disconnect. */
    ServerPlayerEntity player;
    String originalPrompt;

    // ---- Optional reference image (nullable) ----
    byte[] referenceImageBytes;
    String referenceImageMimeType;

    // ---- Agent outputs (written once, then read-only) ----
    BuildSpec spec;                     // set by InterpretationAgent

    // ---- Refactor 3, Phase 0 — concept synthesis outputs ----
    /** All concept images generated by {@code ConceptAgent}. Empty until Phase 0 runs. */
    final List<ReferenceImage> referenceImages = new CopyOnWriteArrayList<>();
    /** Index into {@link #referenceImages} of the Pro-selected primary concept. */
    int selectedConceptIndex;

    // ---- Refactor 3, Phase 1 — 3D mass extraction ----
    /** 16³ voxel silhouette extracted by {@code MassExtractionAgent}. Null until Phase 1 runs. */
    VoxelMass massSketch;
    /** Most recent silhouette drift measurement (§2.3.2); NaN until first compile pass. */
    double lastSilhouetteDrift = Double.NaN;

    // ---- Refactor 3, Phase 2 — cost accounting (§3.1.3) ----
    /** Per-build cost ledger, populated by every {@link com.rayyan.tesseract.api.GeminiClient#call} invocation. */
    final com.rayyan.tesseract.api.CostTracker costTracker = new com.rayyan.tesseract.api.CostTracker();

    // ---- Refactor 3, §3.3.3 — text-only safety fallback ----
    /**
     * When a visual phase (Imagen concept, mass extraction) catastrophically
     * fails, the orchestrator flips this and the pipeline reverts to v2-style
     * text-only blueprinting. Read by future Step 10 wiring.
     */
    boolean textOnlyFallback;

    // ---- Refactor 3, §5 — hierarchical decomposition outputs ----
    /** L1 Architect's top-level massing plan; null until §5.1 runs. */
    com.rayyan.tesseract.plan.MassPlan massPlan;
    /** L2 Decomposer's structural zones (foundation / body / crown / rhythm). Empty until §5.2 runs. */
    final List<com.rayyan.tesseract.plan.StructuralZone> zoneSpecs = new CopyOnWriteArrayList<>();
    /** L3 Element Designer's per-zone elements, already dependency-sorted. Empty until §5.3 runs. */
    final List<com.rayyan.tesseract.plan.ElementSpec> elementSpecs = new CopyOnWriteArrayList<>();

    // ---- Refactor 3, §4.3 — RAG architectural knowledge ----
    /**
     * Top-k corpus entries retrieved for this build's prompt+concept caption.
     * Empty list means either RAG is not ready or retrieval returned nothing.
     * Read by L1/L2/L3 agents so they share a single grounded context block.
     */
    final List<com.rayyan.tesseract.rag.CorpusEntry> ragContext = new CopyOnWriteArrayList<>();
    /**
     * One-line description of the selected concept image, produced by a
     * cheap Gemini Vision caption call (§4.2.3). Concatenated with the
     * user prompt to form the retrieval query. Null until the RagAgent runs.
     */
    String conceptCaption;
    /**
     * Corpus-entry ids that agents have actually cited in their outputs
     * (§4.3.3). Logged in the COMPLETE timeline so we can audit how often
     * retrieval actually influences planning.
     */
    final java.util.Set<String> ragCitations = java.util.concurrent.ConcurrentHashMap.newKeySet();

    // ---- Blueprint DSL pipeline (Refactor 2) ----
    /** Current best Blueprint (updated on each critic patch). Set by BlueprintPlanningAgent. */
    Blueprint blueprint;
    /** Output of the most recent BlueprintCompiler.compile() call. */
    CompiledBlueprint compiledBlueprint;
    /** Number of visual critic passes completed so far. */
    int iterationCount;
    /** Cached isometric render PNG (for critic calls and optional debug export). */
    byte[] lastRenderPng;
    /** Wall-clock ms when the iteration loop started; used for budget enforcement. */
    long iterationStartMs;

    // ---- Placement accumulator ----
    List<BlockOp> completedOps;

    // ---- Spatial context ----
    BlockPos placementOrigin;
    Selection buildSelection;

    // ---- State machine ----
    OrchestratorState state;

    /**
     * Timeline entries appended each time the state machine transitions.
     * Each entry is {@code "STATE_NAME:entryTimeMs"}.
     * Used to build the one-line timeline log at COMPLETE (Step 9.3.3).
     */
    final java.util.List<String> timeline = new java.util.ArrayList<>();
    /** Wall-clock ms when the current state was entered. */
    long stateEnteredAtMs;

    // ---- Event log (CopyOnWriteArrayList — safe to read off server thread) ----
    List<BuildEvent> eventLog;

    // ---- Web build support ----
    /** True for builds triggered via the embedded HTTP server (no real player / world). */
    boolean isWebBuild;
    /**
     * For web builds: completed with the serialised plan JSON once the pipeline
     * reaches COMPLETE, or completed exceptionally on FAILED.
     */
    java.util.concurrent.CompletableFuture<String> webBuildFuture;

    BuildState(UUID playerId, ServerPlayerEntity player, String prompt,
               byte[] imageBytes, String imageMimeType,
               Selection selection) {
        this.playerId = playerId;
        this.player = player;
        this.originalPrompt = prompt;
        this.referenceImageBytes = imageBytes;
        this.referenceImageMimeType = imageMimeType;
        this.buildSelection = selection;
        this.placementOrigin = (selection != null && selection.isComplete())
                ? selection.getMin()
                : BlockPos.ORIGIN;
        this.state = OrchestratorState.IDLE;
        this.stateEnteredAtMs = System.currentTimeMillis();
        this.completedOps = new ArrayList<>();
        this.eventLog = new CopyOnWriteArrayList<>();
        this.iterationCount = 0;
    }
}
